### ISSUE TITLE
astToFields() should follow mongo docs for fields embedded in documents and format the result using dot notation 

### ISSUE THREAD

**Issue by andraLazariuc** [cult-of-coders/apollo-live-server#8]
`astToFields({ metadata: { field1, field2 })` should return `{ "metadata.field1": 1, "metadata.field2" : 1 }`.
Right now it returns `{ metadata : { field1: 1, field2 :1 }` and this is trowing the error "Object in field".

**Comment by theodorDiaconu** [comment]
Solved using `dotize`
